// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCMS.API.Data;

#nullable disable

namespace PCMS.API.Migrations.CaseDb
{
    [DbContext(typeof(CaseDbContext))]
    [Migration("20241006192515_InitialCreate_FirstDbContext")]
    partial class InitialCreate_FirstDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PCMS.API.BusinessLogic.Models.Audit.TestAudit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestAudits");
                });
#pragma warning restore 612, 618
        }
    }
}
